version: 0.2

phases:
  install:
    commands:
      - apt-get update
      - apt-get -y install python-pip
      - pip install --upgrade python
      - pip install --upgrade awscli
  pre_build:
    commands:
      - aws cloudformation validate-template --template-body file://deploy/cfn-release.yaml
      - IMAGE_NAME="${REPOSITORY_URI}:$(echo ${CODEBUILD_RESOLVED_SOURCE_VERSION} | head -c 7)"
      - BASIC_AUTH='"BasicAuthUsername":"","BasicAuthPassword":""'
      - |
        if [ -e "deploy/${ENVIRONMENT_NAME}/env.sh" ]; then
           $( cat "deploy/${ENVIRONMENT_NAME}/env.sh" )
        fi
      - $(aws ecr get-login --no-include-email)
  build:
    commands:
      - echo Build started on $(date)
      - docker build --tag ${IMAGE_NAME} .
      - docker push ${IMAGE_NAME}
  post_build:
    commands:
      - echo Build completed on $(date)
      - printf '{"Parameters":{"ProjectID":"%s","DockerImage":"%s",%s}}' ${PROJECT_ID} ${IMAGE_NAME} ${BASIC_AUTH} > config.json

artifacts:
  files: config.json
